### ISSUE TITLE
Axios dependency

### ISSUE THREAD

**Issue by Xample** [WeslleyDeSouza/payrexx-nodejs#1]
Hi, I get this error when I "npm audit"

> axios  <0.21.1
> Severity: high
> Server-Side Request Forgery - https://npmjs.com/advisories/1594
> No fix available
> node_modules/payrexx/node_modules/axios
>   payrexx  *
>   Depends on vulnerable versions of axios
>   node_modules/payrexx

Solution: Upgrade to 0.21.1 or later

**Comment by WeslleyDeSouza** [comment]
axios updated to 0.21.1

https://github.com/WeslleyDeSouza/payrexx-nodejs/commit/a49a77d78c5b301c44ce6b2468873f1894e248aa
