### ISSUE TITLE
v0.3.0 broken import glitch

### ISSUE THREAD

**Issue by Xample** [WeslleyDeSouza/payrexx-nodejs#2]
Hi, I get the following error
/node_modules/PayRexx/index.ts:1
> import {SubscriptionsActions} from "./actions/payrexx.actions.subscriptions";
> ^^^^^^
> 

This because ts will try to compile *.ts files within the payrexx package, the only *.ts files you should commit are *.d.ts files.

To fix the issue, you should not commit index.ts file, only it's corresponding index.d.ts (by the way a nice place is aside the `index.js` i.e. `dist/index.d.ts`).
![image](https://user-images.githubusercontent.com/944605/112859466-2a68f780-90b3-11eb-9f21-ae84997d05db.png)

then declare explicitly the typings in package.json. To do so, replace

```json
"main": "index.ts",`
```

with 

```json
"main": "dist/index.js",
"types": "dist/index.d.ts",
```

https://medium.com/cameron-nokes/the-30-second-guide-to-publishing-a-typescript-package-to-npm-89d93ff7bccd

**Comment by WeslleyDeSouza** [comment]
Should be fixed in 0.3.5
 https://github.com/WeslleyDeSouza/payrexx-nodejs/commit/2aaea51ddf75b80a7859a02ea619455ff79f85ea

**Comment by Xample** [comment]
this issues has been fixed, for some reason I've another one

```
src/services/payment/payment.service.ts:2:25 - error TS2307: Cannot find module 'PayRexx' or its corresponding type declarations.

2 import { PayRexx } from "PayRexx";
```
But I will check on my side, it's possibly a cache I need to invalidate, I will open another issue if I can identify and isolate the problem. Thank you for your reactivity =)

**Comment by Xample** [comment]
Ok I had to add "allowJs": true  in the tsconfig.json file
```json
{
  "compilerOptions": {
    ...
    "allowJs": true
  }
}
```
 to make it build. This is weird because this only happened with this package and only when I build within a docker container, not on my computer.

**Comment by WeslleyDeSouza** [comment]
import {PayRexx} from "payrexx"; is correct.
it should work without the  "allowJs" flag.

**Comment by Xample** [comment]
okay, I probably got it:

the package.json probably miss the "esModuleInterop": true flag

**Comment by Xample** [comment]
@WeslleyDeSouza it should yes, and does on my computer, but not on docker. I cannot find the precise reason why it does work / or fail, but the issue is there. Anyway, I can keep the allowJs flag for now
