### ISSUE TITLE
Types returned are not exported

### ISSUE THREAD

**Issue by Xample** [WeslleyDeSouza/payrexx-nodejs#3]
Hello Weslley, after updating to the latest version 0.4.3 I realized there is public method returning non exported types

for instance

```typescript
create(params:IGatewayCreate):Promise<Gateway>{
```
Where Gateway is not exported

```typescript
class Gateway implements IGatewayResponse
```

solution: Every type returned by a public method, must be exported as well
```typescript
export class Gateway implements IGatewayResponse {
```

Workaround: right now I can export the type using the following ugly workaround

```typescript
type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
type Gateway = Awaited<ReturnType<PayRexx['gateway']['create']>>
```

**Comment by Xample** [comment]
Okay don't do anything, I will fork and send a merge request

**Comment by WeslleyDeSouza** [comment]
Thanks for you commit! i will merge them!
