### ISSUE TITLE
wrong typing for the `fields` property of the `IGatewayCreate` type

### ISSUE THREAD

**Issue by Xample** [WeslleyDeSouza/payrexx-nodejs#5]
Hi @WeslleyDeSouza

https://github.com/WeslleyDeSouza/payrexx-nodejs/blob/35290042db9aba76120f38638702c2d3827e7713/src/actions/payrexx.actions.gateway.ts#L53

It's not a string, it's a key value on an object containing a value property:

```
fields?: Record<string, { value: string }>
```

I found it by reverse engineering their awesome docs…

current workaround is to force the typing

```typescript
...
'fields': {
   'email': { value: 'test@email.com' },
} as unknown as string,
...
```

Note: I initially wanted to hide the email from their form, if we provide the field at the gateway creation, the email is not mandatory anymore.

**Comment by WeslleyDeSouza** [comment]
Fixed in #[3529004 ](https://github.com/WeslleyDeSouza/payrexx-nodejs/commit/bc5f5db5283884f5dea692e76bc396d3d0ebeafb)
